language: c++
sudo: false

matrix:
  include:
# fully specify builds, include can't dynamically expand matrix entries
# relative order of sudo and env is important so that addons: is recognized

    # linux 64
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
       - TARGET="linux"
       - OPT="gcc4"

    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="linux"
        - OPT="gcc5"

    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="linux"
        - OPT="gcc6"

    # android
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="android"
        - ARCH="armv7"

      # cache:
        # directories:
        # - ~/android-ndk-r15c
        # - apothecary/build/Toolchains/armv7
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="android"
        - ARCH="arm64"

      # cache:
        # directories:
        # - ~/android-ndk-r15c
        # - apothecary/build/Toolchains/arm64

    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="android"
        - ARCH="x86"
      # cache:
        # directories:
        # - ~/android-ndk-r15c
        # - apothecary/build/Toolchains/x86


    # emscripten
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="emscripten"
      services:
        - docker
      before_install:
        - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-incoming-64bit bash


    # linux arm6
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="linuxarmv6l"
        - SYSROOT="$TRAVIS_BUILD_DIR/scripts/$TARGET/raspbian"
        - TOOLCHAIN_ROOT="$TRAVIS_BUILD_DIR/scripts/$TARGET/rpi_toolchain"
        - TOOLCHAIN_PREFIX=arm-linux-gnueabihf


  exclude:
    - compiler: gcc
before_install:
  - scripts/calculate_formulas.sh
install:
  - scripts/$TARGET/install.sh
script:
  - scripts/build.sh
after_success: 
  - |
    TARBALL=openFrameworksLibs_${TRAVIS_BRANCH}_$TARGET$OPT$ARCH$BUNDLE.tar.bz2
    if [ "$TARGET" == "emscripten" ]; then
      run "cd out && tar cjf $TARBALL * && cd .."
      docker cp emscripten:out/${TARBALL} .
    else
      cd out && tar cjf $TARBALL * && cd ..
    fi
  - echo Done

before_deploy:
  - echo Unencrypting key
  - openssl aes-256-cbc -K $encrypted_aa785955a938_key -iv $encrypted_aa785955a938_iv -in scripts/id_rsa.enc -out scripts/id_rsa -d
  - cp scripts/ssh_config ~/.ssh/config
  - chmod 600 scripts/id_rsa
deploy:
  skip_cleanup : true
  provider: script
  script:
    - echo Uploading libraries
    - scp -i scripts/id_rsa $TARBALL tests@ci.openframeworks.cc:libs/$TARBALL.new
    - ssh -i scripts/id_rsa tests@ci.openframeworks.cc "mv libs/$TARBALL.new libs/$TARBALL"
  on:
    branch: md5sum
after_deploy:
  - rm scripts/id_rsa
git:
    depth: 10
