language: c++
sudo: false

matrix:
  include:
# fully specify builds, include can't dynamically expand matrix entries
# relative order of sudo and env is important so that addons: is recognized

    # linux 64
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
       - TARGET="linux"
       - OPT="gcc4"

    # linux arm8
    - os: linux
      cache: ccache
      sudo: required
      dist: trusty
      env:
        - TARGET="linuxarmv8"
        - SYSROOT="$HOME/archlinux"
        - TOOLCHAIN_ROOT="$HOME/rpi4_toolchain"
        - TOOLCHAIN_PREFIX=arm-linux-gnueabihf

  exclude:
    - compiler: gcc
before_install:
  - scripts/calculate_formulas.sh
install:
  - sh scripts/$TARGET/install.sh
script:
  - scripts/build.sh

git:
    depth: 10
