name: build-msys2

on:
  push:
    paths-ignore:
    - '**/README.md'
  pull_request:
    paths-ignore:
    - '**/README.md'

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - mingw: MINGW64
            arch: 64
          - mingw: MINGW32
            arch: 32
    defaults:
      run:
        shell: msys2 {0}
    env: 
      TARGET: msys2
      MSYSTEM: ${{ matrix.mingw }}
      ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          unzip
          dos2unix
          gperf
          ${MINGW_PACKAGE_PREFIX}-libxml2
    - name: Scripts Calc Formula
      run:
        ./scripts/calculate_formulas.sh
    - name: Scripts Install
      run: ./scripts/$TARGET/install.sh
    - name: build
      run: ./scripts/build.sh
